// <auto-generated />
using System;
using API_GrupoFleury.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_GrupoFleury.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211216173352_TableSchedulings")]
    partial class TableSchedulings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("API_GrupoFleury.models.Client", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Cpf")
                        .HasName("Pk_ClientCpf");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("API_GrupoFleury.models.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<double>("Price")
                        .HasPrecision(4, 2)
                        .HasColumnType("double");

                    b.HasKey("Id")
                        .HasName("Pk_ExamId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("API_GrupoFleury.models.Scheduling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateHour")
                        .HasColumnType("datetime");

                    b.Property<double>("Total")
                        .HasPrecision(4, 2)
                        .HasColumnType("double");

                    b.HasKey("Id")
                        .HasName("Pk_SchedulingId");

                    b.ToTable("Schedulings");
                });
#pragma warning restore 612, 618
        }
    }
}
