// <auto-generated />
using System;
using API_GrupoFleury.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_GrupoFleury.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211217173415_UpdateTables")]
    partial class UpdateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("API_GrupoFleury.models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("API_GrupoFleury.models.Client", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(11)");

                    b.HasKey("Cpf")
                        .HasName("Pk_ClientCpf");

                    b.HasIndex("AddressId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("API_GrupoFleury.models.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<double>("Price")
                        .HasPrecision(4, 2)
                        .HasColumnType("double");

                    b.Property<Guid?>("SchedulingId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id")
                        .HasName("Pk_ExamId");

                    b.HasIndex("SchedulingId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("API_GrupoFleury.models.Scheduling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClientCpf")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("HorarioF")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("HorarioI")
                        .HasColumnType("datetime");

                    b.Property<double>("ValueTotal")
                        .HasPrecision(4, 2)
                        .HasColumnType("double");

                    b.HasKey("Id")
                        .HasName("Pk_SchedulingId");

                    b.HasIndex("ClientCpf");

                    b.ToTable("Schedulings");
                });

            modelBuilder.Entity("API_GrupoFleury.models.Client", b =>
                {
                    b.HasOne("API_GrupoFleury.models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("API_GrupoFleury.models.Exam", b =>
                {
                    b.HasOne("API_GrupoFleury.models.Scheduling", null)
                        .WithMany("Exams")
                        .HasForeignKey("SchedulingId");
                });

            modelBuilder.Entity("API_GrupoFleury.models.Scheduling", b =>
                {
                    b.HasOne("API_GrupoFleury.models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientCpf");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("API_GrupoFleury.models.Scheduling", b =>
                {
                    b.Navigation("Exams");
                });
#pragma warning restore 612, 618
        }
    }
}
